### ISSUE TITLE
Can't clone

### ISSUE THREAD

**Issue by wtfcxt** [meisme-dev/Windows-Users-Can-t-Clone-This#2]
help i am a windows user and can't clone this

**Comment by 1x6** [comment]
saem plz help

**Comment by 3w7** [comment]
get linux ez

**Comment by wtfcxt** [comment]
this is ze ärror 
![grafik](https://user-images.githubusercontent.com/53837207/125809123-a6a916a9-e00b-4e0b-8c62-f86d168443e5.png)

**Comment by meisme-dev** [comment]
![image](https://user-images.githubusercontent.com/49573906/125856160-bdcf3fdf-333a-48c3-8de7-53ff7be06ac4.png)

**Comment by wtfcxt** [comment]
ok it worked now i just had to install this os its called linucks? idk somethin like thaht
